#!/usr/bin/env python

from datetime import datetime as dt
import psycopg2
from psycopg2 import extras
import sys

connection = psycopg2.connect(dbname='expenses')

def help_content():
    print('An expense recording system')
    print()
    print('Commands:')
    print()
    print('add AMOUNT MEMO [DATE] - record a new expense')
    print('clear - delete all expenses')
    print('list - list all expenses')
    print('delete NUMBER - remove expense with id NUMBER')
    print('search QUERY - list expenses with a matching memo field')

def return_list():
    try:
        with connection:
            with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
                cursor.execute('''
                    SELECT *
                    FROM expenses
                    ORDER BY created_on;
                ''')
                expenses = cursor.fetchall()
    finally:
        connection.close()

    for expense in expenses:
        columns = [
            str(expense['id']).rjust(3),
            str(expense['created_on']),
            str(expense['amount']).rjust(8),
            str(expense['memo'])
        ]
        print(' | '.join(columns))

def add(amount, memo, date=dt.now().date()):
    try:
        with connection:
            with connection.cursor() as cursor:
                # cursor.execute(f'''
                #     INSERT INTO expenses (amount, memo, created_on) 
                #     VALUES ('{amount}', '{memo}', '{date}');
                # ''')
                cursor.execute(f'''
                    INSERT INTO expenses (amount, memo, created_on) 
                    VALUES (%s, %s, %s);
                ''',(amount, memo, date))
    finally:
        connection.close()

def main():
    if len(sys.argv) > 1:
        command = sys.argv[1]
    else:
        command = None
    
    if command == 'list':
        return_list()
        return
    elif command == 'add':
        if len(sys.argv) < 4:
            print('Error: You must provide an amount and memo.')
            return
        elif len(sys.argv) == 5:
            amount = sys.argv[2]
            memo = sys.argv[3]
            date = sys.argv[4]
            add(amount, memo, date)
            return
        else:
            amount = sys.argv[2]
            memo = sys.argv[3]
            add(amount, memo)
            return
    else:
        help_content()

if __name__ == '__main__':
    main()